#!/bin/sh -e
# https://en.wikibooks.org/wiki/Bash_Shell_Scripting/Whiptail

. ./wealth-src

menu="Welcome to wealth.
What would you like to do?

1. View habits.
2. Create a new habit.
3. Edit habit order.
4. Handle forgotten habits.
5. Mark habits that are uncompleted today.
6. Toggle habit completion.
"

while :
do
	default=5
	sel=$(echo "$menu" | fzf $fzf --header-lines=3)

	# Cancel
	[ "$sel" ] || exit

	case "${sel%%. *}" in
		1) ./wealth-view ;;
		2) exit ;;
		3) exit ;;
		4) exit ;;
		5) exit ;;
		6) exit ;;

		# Invalid input
		*) exit ;;
	esac
done
