#!/bin/sh -e
. ./wealth-src
clear
echo

no_habits="You have not created any habits.
Use the 'Create a new habit.' menu option to create one."

habits=$(mktemp -u)
ls $config/rich > "$habits"
order=$config/wealth/order

list=$(./wealth-order $habits $order)
[ "$list" ] || list=$no_habits

for habit in $list
do
	echo "A $habit A"
done

read
