#!/bin/sh
. wealth-src

name_message="Enter a name for your habit.
Press ESC to cancel."

init_streak_message="What is your current streak for this habit?
Default: 0."

success() {
	# $init_streak should be unquoted so that an empty value isn't taken as an
	# argument ("")
	rich new "$name" $init_streak || exit 1
	echo "$name" >> "$XDG_CONFIG_HOME/wealth/order"

	echo "Successfully created the '$name' habit.
Press Enter to return to the main menu." | $fzf --header-lines=2
	exit 0
}

while :
do
	clear
	name=$(echo "$name_message" | $fzf --header-lines=2 --print-query)
	[ "$name" ] || break

	exists=
	[ -f "$rich_dir/$name" ] && exists=1

	if [ "$exists" ]
	then
		echo "A habit called '$name' already exists.
Press Enter to pick a new name." | $fzf --header-lines=2
		continue
	fi

	init_streak=$(echo "$init_streak_message" | $fzf --header-lines=2 --print-query)

	[ "$exists" ] || success
done
