#!/bin/sh
. wealth-src

clear
file=$(wealth-gen order)
[ -f "$file" ] && order=$(cat "$file")
[ "$order" ] || no_habits

prompt="Select a habit to rename.
Press Escape to cancel.
$order"

sel=$(echo "$prompt" | $fzf --header-lines=2)
[ "$sel" ] || exit

original=${sel##*	}
prompt="Enter a new name for '$original'.
Press Escape to cancel."

name=$(echo "$prompt" | $fzf --header-lines=2 --print-query)
[ "$name" ] || exit

[ -f "$rich_dir/$name" ] &&
	echo "ERR A habit called '$name' already exists." &&
	exit 1

cd "$rich_dir"
mv "$original" "$name"

cd "$XDG_CONFIG_HOME/wealth"
sed -i "s/^$original$/$name/g" order
sed -i "s/,$original,/,$name,/g" forgot

echo "Successfully renamed $original --> $name.
Press Enter to return to the main menu." | $fzf --header-lines=2
