#!/bin/sh -e
. wealth-src

menu="Welcome to wealth.
What would you like to do?

1. View habits.
2. Create a new habit.
3. Edit habit order.
4. Handle forgotten habits.
5. Mark habits that are uncompleted today.
6. Toggle habit completion.
7. Manually set a habit's streak count.
8. Rename a habit.
9. Delete a habit.
10. Exit the program."

while :
do
	sel=$(echo "$menu" | $fzf --header-lines=3)

	# Cancel
	[ "$sel" ] || exit

	case "${sel%%. *}" in
		1) wealth-view ;;
		2) wealth-create ;;
		3) $EDITOR $XDG_CONFIG_HOME/wealth/order ;;
		4) wealth-forgot ;;
		5) wealth-mark ;;
		6) wealth-toggle ;;
		7) wealth-set ;;
		8) wealth-rename ;;
		9) wealth-delete ;;
		10) exit ;;
	esac
done
