#!/bin/sh
. wealth-src

todo=$(mktemp -u)
rich todo > "$todo"

order=$(wealth-gen order)
ordered_todo=$(mktemp -u)
while read -r habit
do
	grep "^$habit\$" "$todo" >> "$ordered_todo"
done < "$order"

parsed_todo=$(mktemp -u)
while read -r habit
do
	count=$(rich streak "$habit")
	echo "[$count]	$habit" >> "$parsed_todo"
done < "$ordered_todo"

if [ ! -f "$parsed_todo" ]
then
	clear
	echo "You do not have any habits to complete.
Press Enter to return to the main menu." | $fzf --header-lines=2
	exit 0
fi

gen_header() {
	echo "These habits have not been completed today.
Selecting one will mark it as complete.
Press ESC to return to the main menu.

$(cat $parsed_todo)"
}


while :
do
	# Exit once there are no habits to complete instead of making a
	# dysfunctional, confusing prompt
	[ "$(cat "$parsed_todo")" ] || exit 0

	sel=$(gen_header | $fzf --header-lines=4)
	[ "$sel" ] || exit 0
	sel=${sel##*	}

	rich mark "$sel"
	sed -i "/\t$sel$/d" "$parsed_todo"
done
