#!/bin/sh
. wealth-src

clear
file=$(wealth-gen toggle)
[ -f "$file" ] && toggle=$(cat "$file")
[ "$toggle" ] || no_habits

prompt="Select a habit to modify.
Press Escape to cancel.
$toggle"

sel=$(echo "$prompt" | $fzf --header-lines=2)
[ "$sel" ] || exit 0

habit=${sel##*	}
prompt="What streak number do you want to set
$habit (${sel%	*})
to? Press Escape to cancel."

streak=$(echo "$prompt" | $fzf --header-lines=3 --print-query)
[ "$streak" ] || exit 0

rich set "$habit" "$streak" || exit 1

echo "Successfully set $habit's streak to $streak.
Press Enter to return to the main menu." | $fzf --header-lines=2
exit 0
