#!/bin/sh
. ./wealth-src

gen_menu() {
	file=$(./wealth-gen toggle)
	[ -f "$file" ] && toggle=$(cat "$file")

	[ "$toggle" ] || echo "$no_habits"
	[ "$toggle" ] && echo "[X]: Completed today
[ ]: Not completed today

Select a habit to toggle completion.
Press ESC to return to the main menu.

$toggle"
}

while :
do
	sel=$(gen_menu | fzf $fzf --header-lines=6)
	[ "$sel" ] || break

	habit=${sel##*	}
	[ "${sel%% *}" = "[" ] && rich mark "$habit"
	[ "${sel%% *}" = "[X]" ] &&
		count=${sel##* } &&
		count=${count%%	*} &&
		count=$(echo "$count" | sed "s/[][]//g") &&
		rich delete "$habit" &&
		rich new "$habit" "$((count-1))"
done
