#!/bin/sh
. wealth-src

clear
file=$(wealth-gen order)
[ -f "$file" ] && order=$(cat "$file")
[ "$order" ] || no_habits

prompt="Select a habit to delete.
Press Escape to cancel.
$order"

sel=$(echo "$prompt" | $fzf --header-lines=2)
[ "$sel" ] || exit 0

habit=${sel##*	}
prompt="Are you sure you want to delete '$habit'?
Type 'yes' to confirm the deletion. Press Escape to cancel."

name=$(echo "$prompt" | $fzf --header-lines=2 --print-query)
[ "$name" = yes ] || exit 0

rich delete "$habit"
cd "$XDG_CONFIG_HOME/wealth"
sed -i "/^$habit$/d" order
sed -i "/,$habit,/d" forgot

echo "Successfully deleted '$habit'.
Press Enter to return to the main menu." | $fzf --header-lines=2
exit 0
