#!/bin/sh -e
. wealth-src

clear
file=$(wealth-gen toggle)
[ -f "$file" ] && toggle=$(cat "$file")
[ "$toggle" ] || no_habits

tmp=$(mktemp -u)
echo "Your habits:
$toggle

Press Enter to return to the main menu." > "$tmp"

wc=$(wc -l "$tmp")
wc=${wc%% *}

$fzf --header-lines=$wc < "$tmp"
