#!/bin/sh

name=${1##*/}
date=$2
number=$3

# Generate unique identifier
# ($RANDOM and $(date +%s) wouldn't change fast enough)
tmp=$(mktemp -u)
echo "$RANDOM $name" > "$tmp"
id=$(md5sum "$tmp")
id=${id%% *}

echo "$id\t$name\t$date\t$number" >> $XDG_CONFIG_HOME/wealth/forgot
