#!/bin/sh
fzf="--reverse --bind=tab:down,btab:up,alt-k:up,alt-j:down --cycle"
no_habits="You have not created any habits.
Use the 'Create a new habit.' menu option to create one."

# Update any dates/forgets
RICH_HOOK=wealth-hook rich > /dev/null
