#!/bin/sh
. wealth-src

case "$1" in
	order)
		habits=$(mktemp -u)
		ls "$rich_dir" > "$habits"
		order=$XDG_CONFIG_HOME/wealth/order

		output=$(mktemp -u)
		wealth-order "$habits" "$order" | sed "/^\$/d" > "$output"
		echo "$output" ;;

	toggle)
		order=$(wealth-gen order)
		toggle=$(mktemp -u)

		while read -r habit
		do
			rich todo "$habit" > /dev/null &&
				status="[ ]" ||
				status="[X]"
			count=$(rich streak "$habit")

			echo "$status [$count]	$habit" >> "$toggle"
		done < "$order"

		echo "$toggle" ;;

	*)
		echo "ERR Invalid usage"
		exit 1 ;;
esac
